export const CALC_TODAY_COMMON = "CALC_TODAY_COMMON";
export const CALC_TODAY_FUN = "CALC_TODAY_FUN";

export const GET_ALL_COSTS_REQUEST = "GET_ALL_COSTS_REQUEST";
export const GET_ALL_COSTS_FAILURE = "GET_ALL_COSTS_FAILURE";
export const GET_ALL_COSTS_SUCCESS = "GET_ALL_COSTS_SUCCESS";

export const CALC_TODAY_COSTS_REQUEST = "CALC_TODAY_COSTS_REQUEST";
export const CALC_TODAY_COSTS_SUCCESS = "CALC_TODAY_COSTS_SUCCESS";
export const CALC_TODAY_COSTS_FAILURE = "CALC_TODAY_COSTS_FAILURE";
