export const ADD_PAYDAY_REQUEST = "ADD_PAYDAY_REQUEST";
export const ADD_PAYDAY_SUCCESS = "ADD_PAYDAY_SUCCESS";
export const ADD_PAYDAY_FAILURE = "ADD_PAYDAY_FAILURE";
export const GET_PAYDAY_REQUEST = "GET_PAYDAY_REQUEST";
export const GET_PAYDAY_SUCCESS = "GET_PAYDAY_SUCCESS";
export const GET_PAYDAY_FAILURE = "GET_PAYDAY_FAILURE";
