export const PROFILE_OPERATION_REQUEST = "PROFILE_OPERATION_REQUEST";
export const PROFILE_OPERATION_SUCCESS = "PROFILE_OPERATION_SUCCESS";
export const PROFILE_OPERATION_FAILURE = "PROFILE_OPERATION_FAILURE";
