export const TOGGLE_VK_CLIENT_SUCCESS = "TOGGLE_VK_CLIENT_SUCCESS";
export const TOGGLE_VK_CLIENT_REQUEST = "TOGGLE_VK_CLIENT_REQUEST";
export const TOGGLE_VK_CLIENT_FAILED = "TOGGLE_VK_CLIENT_FAILED";

export const TOGGLE_CUSTOM_DARK_THEME_SUCCESS =
  "TOGGLE_CUSTOM_DARK_THEME_SUCCESS";
export const TOGGLE_CUSTOM_DARK_THEME_REQUEST =
  "TOGGLE_CUSTOM_DARK_THEME_REQUEST";
export const TOGGLE_CUSTOM_DARK_THEME_FAILED =
  "TOGGLE_CUSTOM_DARK_THEME_FAILED";
