//@flow
export const TUTORUAL_CHANGE_SUCCESS = "TUTORUAL_CHANGE_SUCCESS";
export const TUTORIAL_CHANGE_REQUEST = "TUTORIAL_CHANGE_REQUEST";
export const TUTORUAL_CHANGE_ERROR = "TUTORUAL_CHANGE_ERROR";
