export const ADD_BUDGET_REQUEST = "ADD_BUDGET_REQUEST";
export const ADD_BUDGET_SUCCESS = "ADD_BUDGET_SUCCESS";
export const ADD_BUDGET_FAILURE = "ADD_BUDGET_FAILURE";

export const GET_BUDGET_REQUEST = "GET_BUDGET_REQUEST";
export const GET_BUDGET_SUCCESS = "GET_BUDGET_SUCCESS";
export const GET_BUDGET_FAILURE = "GET_BUDGET_FAILURE";

export const CALC_BUDGET_REQUEST = "CALC_BUDGET_REQUEST";
export const CALC_BUDGET_FAILURE = "CALC_BUDGET_FAILURE";
export const CALC_BUDGET_SUCCESS = "CALC_BUDGET_SUCCESS";
