# Generated by Django 2.1.4 on 2019-03-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vkuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vk', models.TextField(max_length=50)),
                ('budget', models.TextField(max_length=100)),
                ('pay_day', models.TextField(max_length=100)),
            ],
        ),
    ]
