# Generated by Django 2.1.7 on 2019-03-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='max_for_today',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
