# Generated by Django 2.1.7 on 2019-04-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20190331_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vkuser',
            old_name='max_for_today_common',
            new_name='common',
        ),
        migrations.RenameField(
            model_name='vkuser',
            old_name='max_for_today_fun',
            new_name='fun',
        ),
        migrations.AddField(
            model_name='vkuser',
            name='invest',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
