# Generated by Django 2.1.7 on 2019-04-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20190401_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='days_to_payday',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
